---
title: "Atelier 4"
author: "Téa Motte"
date: "11/13/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
nutriage <- read.csv("~/Desktop/Atelier4-master/nutriage.csv")
names(nutriage)
```

```{r}
hirst(nutriage$taille)
summary(nutriage$taille)
```
H : taille $\sim N (\mu,\sigma)$ le probleme est $\(taille<0) > 0$
```{r}
mean (nutriage$taille)
sd(nutriage$taille)
```
calculer $\Pr(taille < 0)$ avec $taille \sin N(163.9602,9.003368)$

```{r}
pnorm (0, mean(nutriage$taille),sd(nutriage$taille))
```

#option 2

Soit $taille=e^x avec $ X \sim N(mu,\sigma) $

```{r}
X <- log(nutriage$taille)
hist(X)
```

```{r}
X <- log(nutriage$taille)
hist(X)
summary(X)
Q <- seq(from=0, to=1,by=0.1)
Q
qnorm(Q)
```
qq-plot

```{r}
Z <- (X-mean(X))/sd(X)
n <- length(Z)
n
Normal <- rnorm(n)
qqplot(Normal,Z,xlim=c(-3,3),ylim=c(-3,3))
par(new=T)
plot(Z,Z,type="l",col="red",xlim = c(-3,3),ylim =c(-3,3),xlabel="",ylabel="")
      
```

```{r}
nutriage <- read.csv("~/Desktop/Atelier4-master/nutriage.csv")
names(nutriage)
```

```{r}
hirst(nutriage$poids)
summary(nutriage$poids)
```
H : taille $\sim N (\mu,\sigma)$ le probleme est $\(taille<0) > 0$
```{r}
mean (nutriage$poids)
sd(nutriage$poids)
```
calculer $\Pr(taille < 0)$ avec $taille \sin N(163.9602,9.003368)$

```{r}
pnorm (0, mean(nutriage$poids),sd(nutriage$poids))
```

#option 2

Soit $taille=e^x avec $ X \sim N(mu,\sigma) $

```{r}
X <- log(nutriage$poids)
hist(X)
```

```{r}
X <- log(nutriage$poids)
hist(X)
summary(X)
Q <- seq(from=0, to=1,by=0.1)
Q
qnorm(Q)
```

```{r}
Z <- (X-mean(X))/sd(X)
n <- length(Z)
n
Normal <- rnorm(n)
qqplot(Normal,Z,xlim=c(-3,3),ylim=c(-3,3),xlab = "Normal",ylab = "log(poids")
par(new=T)
plot(Z,Z,type="l",col="red",xlim = c(-3,3),ylim =c(-3,3),xlabel="",ylab="")
      
```


cafe 
```{r}
table (nutriage$cafe)
mean(nutriage$cafe)
var(nutriage$cafe)
lambda <- (mean(nutriage$cafe)+var(nutriage$cafe))/2
lambda
simul <- rpois(1000, lambda)
table(simul)
```

```{r}
table (nutriage$the)
mean(nutriage$the)
var(nutriage$the)
lambda <- (mean(nutriage$the)+var(nutriage$the))/2
lambda
simul <- rpois(1000, lambda)
table(simul)
```










